<a href="https://colab.research.google.com/github/mohamedyasser21/MachineLearning/blob/main/last.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
import re
import string
from sklearn.naive_bayes import MultinomialNB

In [3]:
df_fake = pd.read_csv("Fake.csv")
df_true = pd.read_csv("True.csv")

In [ ]:
df_fake.head()


In [ ]:
df_true.head(5)

In [6]:
df_fake["class"] = 0
df_true["class"] = 1

In [7]:
df_merge = pd.concat([df_fake, df_true], axis =0 )
df_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [ ]:
df_merge.columns

In [9]:
df = df_merge.drop(["title", "subject","date"], axis = 1)

In [10]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [11]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [12]:
df["text"] = df["text"].apply(wordopt)

In [13]:
x = df["text"]
y = df["class"]

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [30]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train,y_train)
pred_lr=LR.predict(xv_test)
LR.score(xv_test, y_test)
print(classification_report(y_test, pred_lr))

auc_score = roc_auc_score(y_test, pred_lr)
print("\nROC AUC Score:",auc_score)
cm = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix\n")
print(cm)

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5924
           1       0.98      0.99      0.99      5301

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225


ROC AUC Score: 0.9863771037556646
Confusion Matrix

[[5833   91]
 [  63 5238]]


In [31]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)
pred_dt = DT.predict(xv_test)
pred_dt = DT.predict(xv_test)
print(classification_report(y_test, pred_dt))
auc_score = roc_auc_score(y_test, pred_lr)
print("\nROC AUC Score:",auc_score)
cm = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix\n")
print(cm)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      5924
           1       1.00      0.99      1.00      5301

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225


ROC AUC Score: 0.9863771037556646
Confusion Matrix

[[5833   91]
 [  63 5238]]


In [32]:
from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier(random_state=0)
GBC.fit(xv_train, y_train)
pred_gbc = GBC.predict(xv_test)
GBC.score(xv_test, y_test)
print(classification_report(y_test, pred_gbc))
auc_score = roc_auc_score(y_test, pred_lr)
print("\nROC AUC Score:",auc_score)
cm = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix\n")
print(cm)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5924
           1       0.99      1.00      1.00      5301

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225


ROC AUC Score: 0.9863771037556646
Confusion Matrix

[[5833   91]
 [  63 5238]]


In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(xv_train, y_train)
pred_knn = GBC.predict(xv_test)
knn.score(xv_train, y_train)
print("Accuracy:",knn.score(xv_test, y_test))
print(classification_report(y_test, pred_knn))
auc_score = roc_auc_score(y_test, pred_lr)
print("\nROC AUC Score:",auc_score)
cm = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix\n")
print(cm)

Accuracy: 0.7926057906458798
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5924
           1       0.99      1.00      1.00      5301

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225


ROC AUC Score: 0.9863771037556646
Confusion Matrix

[[5833   91]
 [  63 5238]]


In [20]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models
from nltk.tokenize import word_tokenize
import tokenize 
from keras.preprocessing.text import Tokenizer

In [34]:
from sklearn.metrics.pairwise import linear_kernel
# Initialize the Multinomial Naive Bayes classifier
nb = MultinomialNB()

# Fit the model
nb.fit(xv_train, y_train)
nb.score(xv_train, y_train)
pred_nb = GBC.predict(xv_test)
print("Accuracy:",nb.score(xv_test, y_test))
print(classification_report(y_test, pred_nb))
auc_score = roc_auc_score(y_test, pred_lr)
print("\nROC AUC Score:",auc_score)
cm = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix\n")
print(cm)


Accuracy: 0.9363919821826281
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5924
           1       0.99      1.00      1.00      5301

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225


ROC AUC Score: 0.9863771037556646
Confusion Matrix

[[5833   91]
 [  63 5238]]


In [36]:
from sklearn import svm
SVM = svm.SVC(C=1.0, kernel='linear', gamma='auto')
SVM.fit(xv_train, y_train)# predict the labels on validation dataset
predictions_SVM = SVM.predict(xv_test)# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, y_test)*100)

SVM Accuracy Score ->  99.41202672605792
